# Generated by Django 3.1.7 on 2021-03-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0003_deck_like_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='枚数'),
        ),
        migrations.AddField(
            model_name='character',
            name='num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='枚数'),
        ),
    ]
