# Generated by Django 3.1.7 on 2021-03-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0004_auto_20210307_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='group',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
